# openapi: '3.0.2'
# info:
#   title: Airbnb
#   description: Alta Project 
#   license:
#     name: Apache 2.0
#     url: https://www.apache.org/licenses/LICENSE-2.0.html
#   version: '1.0'
# servers:
#   - description: SwaggerHub API Auto Mocking
#     url: https://virtserver.swaggerhub.com/Nathannov24/Airbnb/1.0
#     variables:
#       environment: 
#         default: dev
#         enum:
#           - "prod"
#           - "dev"
# tags:
#   - name : Auth
#     description: Authentication
#   - name : Users
#     description: User control
# paths:
#   /test:
#     get:
#       responses:
#         '200':
#           description: OK